name: Run tests

on:
  push:
  #   branches:
  #     - '*'
  #   paths:
  #     - 'TurboTest/**'
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  workflow_dispatch:

jobs:
  on:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      
      ## ~~delete this soon (after using mykit builder).~~
      ## Note from my future self: Actually, this line will remain here since testing will not
      ## require any build. So, it will still require this line, but the version will depend on
      ## the one specified in the source code (not the latest version that is available).
      - run: pip install mykit==10.0.0b10
      
      - run: python -m unittest -v
